### ISSUE TITLE
Update the index page

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#11]
We have Next.js's default index page on the index page.

We should change that
![image](https://github.com/ykdojo/kaguya/assets/1811651/a75b7b75-bd10-43e5-91d6-153f4567a97a)

**Comment by ykdojo** [comment]
This fixes #8.

**Comment by zenchantlive** [comment]
could we use the vercel starter to get us going? [https://github.com/vercel-labs/ai/tree/main/examples/next-openai](vercel-next.js-openai-starter)

**Comment by ykdojo** [comment]
I don't think that's necessary.

I think what we need is a page that describes what this app does - wdyt? @zenchantlive

**Comment by ThirDecade2020** [comment]
I miraculously encountered this page today setting up localhost:3000 so I actually know what it is now haha...I could take on this assignment I took a look and see changes will happen in Index.js code? What message do you want to put here?

**Comment by ykdojo** [comment]
Sure! What do you think should be there?

**Comment by ThirDecade2020** [comment]
I went through all the steps and set up localhost:3000 successfully on my local machine. When the web-page popped up though I didn't quite understand how it played a part in the final goal of interacting with Kaguya/GPT4.

Perhaps throw up the CS Dojo logo and underneath a brief description of localhost purpose in Kaguya/GPT4 context, add final steps to start interacting, and fall into a brief description of Kaguya's capabilities as said above in thread.

If I am off in any way here just let me know.

**Comment by ykdojo** [comment]
That sounds pretty good.

In the latest commit of mine (https://github.com/ykdojo/kaguya/commit/0d57f76c9471e721385fa2a38e47488d82c7cf0b), I actually ended up editing the index page a bit and added a link to the API doc page.

I hope it's helpful. If you feel like we need something on top of that, maybe stuff you mentioned, definitely let me know, too.

**Comment by ThirDecade2020** [comment]
This looks clean & relevant compared to previous version. Close up issue?

![1](https://github.com/ykdojo/kaguya/assets/115199204/3409af7e-25a5-46b8-8e8f-229338ec8a36)

![2](https://github.com/ykdojo/kaguya/assets/115199204/53203944-5599-423e-ba57-d379fb184920)

**Comment by ykdojo** [comment]
If you think it's clear & clean enough, sure, we can close it

**Comment by ThirDecade2020** [comment]
Now that I've finally gone through all the steps to interact with Kaguya, & have a rough grasp of this process, I do think it's clear & clean enough ha! API endpoints link/page look good hopefully I can try out more POSTS in near future.
