### ISSUE TITLE
Apply for ChatGPT developer permissions？

### ISSUE THREAD

**Issue by Xuzan9396** [ykdojo/kaguya#13]
Apply for ChatGPT developer permissions？

**Comment by ykdojo** [comment]
@Xuzan9396 what do you mean exactly?

**Comment by Xuzan9396** [comment]
How to add the chatgpt plugin, access localhost, and analyze local files.
![image](https://github.com/ykdojo/kaguya/assets/24741439/25622167-6b97-4ae4-976f-4b16b8034a6d)

**Comment by ykdojo** [comment]
Do you have ChatGPT plugin dev access?

**Comment by jmanhype** [comment]
> Do you have ChatGPT plugin dev access?

why are you acting like you clearly stated this in the README... you did not this repo is awesome but you poorly documented anything regarding it. please do better. you can even have chat gpt do a write up for you lmao

**Comment by ykdojo** [comment]
If you don't like the documentation, feel free to send a PR to fix it

**Comment by Xuzan9396** [comment]
@ykdojo  I've already applied, but I don't know how long to wait
<img width="903" alt="image" src="https://github.com/ykdojo/kaguya/assets/24741439/5605b5fb-2685-4b9b-be18-c808320d6806">
