### ISSUE TITLE
have you tried writing any documentation

### ISSUE THREAD

**Issue by elliotberry** [ykdojo/kaguya#14]

**Comment by ykdojo** [comment]
@elliotberry can you clarify your question?

**Comment by jmanhype** [comment]
> @elliotberry can you clarify your question?

my boy theey alll trying to tell you the docs suckk lol

**Comment by ykdojo** [comment]
@jmanhype sure, feel free to send a PR to fix it

**Comment by jmanhype** [comment]
Good luck getting people to Pr this
