### ISSUE TITLE
Create a more thorough getting started guide

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#18]
The pinned messages on #kaguya channel on our Discord (https://discord.com/invite/nNtVfKddDD) should be a good reference for this.

**Comment by ThirDecade2020** [comment]
I opened settings in ChatGPT today and happy to see that I was granted plugin dev access. I am at the starting point in Kaguya, and this is pretty much my first time seriously collaborating on Github, so I can be a good test run for how to get someone booted up to participate in an advanced repository from 0. I combed through the Discord channel but not sure what to focus on first can you elaborate more here? Thanks!

**Comment by elidakirigo** [comment]
hi, I'd like to contribute to the documentation of this project.

**Comment by ykdojo** [comment]
@elidakirigo sure that'll be great. Thank you

**Comment by elidakirigo** [comment]
okay

**Comment by ykdojo** [comment]
Let me know here if you have any questions

**Comment by elidakirigo** [comment]
okay @ykdojo thanks

**Comment by ykdojo** [comment]
@ThirDecade2020 did you have a chance to take a look at the pinned messages?

**Comment by ThirDecade2020** [comment]
@ykdojo yes I saw & working on it, currently setting up workflow via CLI/GIT/VSCode/Github will bring up any blocks here thx

**Comment by ThirDecade2020** [comment]
on Docker installation & confused how to get started via linux/pixelbook ty

**Comment by ThirDecade2020** [comment]
GPT-4 down at moment, but Bing chat really picked up the slack in a great way...Docker version 24.0.4 installed & via terminal ran ```sudo docker run hello-world``` to check & ok but have to add ```sudo``` at beginning of every command or won't run, will that be an issue down the road? on to step #3...

**Comment by ykdojo** [comment]
Yes sounds good
