### ISSUE TITLE
Move the demo videos up in README

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#20]
The demo videos should be right after the initial intro so that we can show people the potential of this project more quickly.

**Comment by pushkaraj2007** [comment]
@ykdojo

You mean instead of linking to demo videos, place them directly into the readme, right?

I can work on this issue. Can you please assign this to me?

**Comment by ykdojo** [comment]
@pushkaraj2007 I meant just moving the sections around, but sure, embedding videos directly might work well too.
