### ISSUE TITLE
On README, mention plugin dev access

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#25]
You need ChatGPT's plugin dev access to set this up.

Mention this and maybe add a link to their waitlist too.

**Comment by ThirDecade2020** [comment]
I can take this issue if ok. I guess message/link should be placed at end of opening h1 paragraph?

**Comment by ykdojo** [comment]
It should be part of the getting started guide or something similar to that.

**Comment by ThirDecade2020** [comment]
'Getting Started Guide' is to be inserted into 'README'? who is assigned to 'GSG'? Another option is to mention it at the end of the first paragraph in the 'README' where it discusses GPT right at top of doc until 'GSG' is ready...

**Comment by ykdojo** [comment]
What do you think is the best approach here?

**Comment by ThirDecade2020** [comment]
README already seems to be the place to plugin all high-level info for someone new looking at Kaguya so Getting Started Guide section should be included there at top of doc. Roughly: 1) Gain dev access (or other option if unable) 2) Install Docker if not already installed 3) Execute docker.sh script 4) setup localhost port 3000 5) Interact with Kaguya 6) Open-source. There are sub-steps within each step for setup that might be difficult for a beginner so those could be included too. Thoughts?

**Comment by ykdojo** [comment]
Sounds good! Feel free to send a draft PR if you want to go step by step, or a full PR if you prefer it that way

**Comment by ThirDecade2020** [comment]
ok thx - back at this today will keep updated
