### ISSUE TITLE
Docker produces error on Windows

### ISSUE THREAD

**Issue by AnBenLa** [ykdojo/kaguya#29]
Running the docker application on Windows 10 produces the following error:
```javascript
> hako-next@0.1.0 dev /kaguya
> if [ -f /.dockerenv ]; then next dev; else echo 'Error: Please run this script inside a Docker container.' && exit 1; fi
Watchpack Error (watcher): Error: EACCES: permission denied, watch '/root'
Watchpack Error (initial scan): Error: EACCES: permission denied, scandir '/root'
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Project directory could not be found, restart Next.js in your new directory
```

**Comment by ykdojo** [comment]
I believe there was a discussion about this on our Discord. Mind checking there?

**Comment by AnBenLa** [comment]
Sure, I will do. Thanks for the quick reply!

> I believe there was a discussion about this on our Discord. Mind checking there?

**Comment by ykdojo** [comment]
No problem.

I think this might be the solution I was referring to. Let me know if it works: https://discord.com/channels/1007344194622324807/1120722773879300257/1121965413480267837
