### ISSUE TITLE
Error in deleteDirectory syntax

### ISSUE THREAD

**Issue by wonderwhy-er** [ykdojo/kaguya#31]
There is an error here
https://github.com/ykdojo/kaguya/blob/master/pages/api/deleteDirectory.js#L5

It tries to modify directoryPath right in parameters
I guess ChatGPT wrote that :D

I just changed it from to
```js
function deleteDirectoryRecursively(path.join(process.cwd(), 'FILES', directoryPath)) {
```
to

```js
function deleteDirectoryRecursively(directoryPath) {
  directoryPath = path.join(process.cwd(), 'FILES', req.query.directoryPath);
```

**Comment by ykdojo** [comment]
[This commit](https://github.com/ykdojo/kaguya/commit/d77cf68f1d935c5e48048d154f3a0cc4e40a0bfe) should've fixed it - let me know if it doesn't work.

ty for raising this issue!
