### ISSUE TITLE
Add a recommended custom instruction on README

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#32]
Now that OpenAI has Custom Instructions (a persistent instruction for new conversations), we should show a recommended custom instruction on README.

Currently, I have this:

```
When editing a file, use search and replace and NOT updateWholeFile unless we're dealing with a very small file. Confirm with me before you edit a file.

When you have output from Kaguya, there's no need to repeat everything from there. Instead, you can summarize it concisely.

When you want to use executeCommand in a subdirectory, make sure to cd there first every time.
```

I might refine it as I go, but it should be good enough for now.

**Comment by ThirDecade2020** [comment]
Please assign this to me. Anything else you want to add to Custom Instructions?

**Comment by ykdojo** [comment]
No I think they're ok as is for now!
