### ISSUE TITLE
Share this on Hacker News?

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#4]

**Comment by Madprojets** [comment]
hey ykdojo

**Comment by ykdojo** [comment]
?

**Comment by jacob-dietle** [comment]
I think you absolutely should! This an awesome tool and I'm sure it would get a lot of traction. I would suggest creating a setup tutorial first to reduce the number of future issues like the "have you tried writing documentation" from the influx it will probably bring and save yourself the potential headache. Like I mentioned in discord, I'm happy to contribute to the win setup portion with a PR to the readme when I have some time :)

**Comment by ykdojo** [comment]
Sounds good! That's basically where I was, too. And thank you! Looking forward to your PR.
