### ISSUE TITLE
Add a link to YK's GitHub sponsorship page

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/kaguya#5]

**Comment by adilwahla** [comment]
I am gonna fix this assign me :)

**Comment by ykdojo** [comment]
@adilwahla it's been a month, so I'm going to un-assign you.

**Comment by ThirDecade2020** [comment]
Do you want link at end of README?

**Comment by ykdojo** [comment]
Ty for the question - it should be configured in a way where it shows up at the top of the repo.

**Comment by ThirDecade2020** [comment]
Feel free to assign me here! TY

**Comment by ykdojo** [comment]
@ThirDecade2020 done, thank you!

**Comment by ykdojo** [comment]
Actually I decided to close this one for now since I added a link to Kaguya's waitlist instead: http://kaguya.ai/
