### ISSUE TITLE
Docker only brings me to "create next app" homepage

### ISSUE THREAD

**Issue by zenchantlive** [ykdojo/kaguya#8]
this makes sense given the files. however, this means the app is not built. Am i correct? I wanted to use this but it seems the code is missing lol 

if I am just super early or something, that is cool! just now sure what is going on here as there is not any code representative of your demos. Am I doing something wrong?

https://github.com/ykdojo/kaguya/assets/103866469/36e380c5-ebd9-4710-b5fa-675ef9f62d13

**Comment by ykdojo** [comment]
The app is already built. You'll need to connect it from ChatGPT. Do you have plugin dev access?

**Comment by zenchantlive** [comment]
no, i do not, dang, i did not realize i would need that.

**Comment by ThirDecade2020** [comment]
I think this issue has been solved with updated index/README etc?
